### ISSUE TITLE
Bugs in the user simulator

### ISSUE THREAD

**Issue by ggordonhall** [ConvLab/ConvLab#64] opened 2019-09-03 10:38 UTC
Hi, while training ConvLab I've discovered a couple of bugs in the user simulator:

1)  Sometimes the `check_constraint` function in `policy_agenda_multiwoz.py` (line 254) is passed the string "soonest" for`val_usr`. The function expects times in the form `XX:YY`, cannot resolve "soonest", and therefore throws an error.

2) The function `get_request_state` in `multiwoz_state_encoder.py` (line 69) throws an error when it tries to get in the index of the `pricerange` slot in `REF_USR_DA[Attraction]`. This slot does not exist in the `Attraction` domain of `REF_USR_DA`. 

Can you implement a fix?

Thanks!
Gabriel

**Comment by truthless11** [comment] 2019-09-04 03:23
@ggordonhall Thanks for reporting the issue. The first problem has been fixed now. 

In terms of the second problem, the slot type `pricerange` should **not** exist in the `Attraction` domain, though the DB file exists. Could you show us the details of the error you met?

**Comment by xylankant** [comment] 2019-09-04 12:52
Hello,

The bug for us occurs when training e2e with a user simulator that is, when using NLU and NLG in both Agent and User settings. Below is a stack trace of the error occurring:

> Process Process-2:
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
>     self.run()
>   File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/philipjg/dstc8/ConvLab/convlab/experiment/control.py", line 35, in mp_run_session
>     metrics = session.run()
>   File "/home/philipjg/dstc8/ConvLab/convlab/experiment/control.py", line 170, in run
>     self.run_rl()
>   File "/home/philipjg/dstc8/ConvLab/convlab/experiment/control.py", line 133, in run_rl
>     self.try_ckpt(self.agent, self.env)
>   File "/home/philipjg/dstc8/ConvLab/convlab/experiment/control.py", line 87, in try_ckpt
>     self.num_eval)
>   File "/home/philipjg/dstc8/ConvLab/convlab/experiment/analysis.py", line 68, in gen_avg_result
>     returns.append(gen_result(agent, env))
>   File "/home/philipjg/dstc8/ConvLab/convlab/experiment/analysis.py", line 59, in gen_result
>     _return = gen_return(agent, env)
>   File "/home/philipjg/dstc8/ConvLab/convlab/experiment/analysis.py", line 36, in gen_return
>     agent.update(obs, action, reward, next_obs, done)
>   File "/home/philipjg/dstc8/ConvLab/convlab/agent/__init__.py", line 202, in update
>     input_act, next_state, encoded_state = self.state_update(next_obs, action)
>   File "/home/philipjg/dstc8/ConvLab/convlab/agent/__init__.py", line 177, in state_update
>     encoded_state = self.state_encoder.encode(state) if self.state_encoder else state
>   File "/home/philipjg/dstc8/ConvLab/convlab/modules/state_encoder/multiwoz/multiwoz_state_encoder.py", line 18, in encode
>     request_vector = self.get_request_state(state['request_state'])
>   File "/home/philipjg/dstc8/ConvLab/convlab/modules/state_encoder/multiwoz/multiwoz_state_encoder.py", line 69, in get_request_state
>     domain_vector[list(REF_USR_DA[domain.capitalize()].keys()).index(slot)] = 1
> ValueError: 'pricerange' is not in list


Also, in this particular instance it seems like this error is thrown immediately after another exception. This could be a coincidence/another bug, or it could be related. The stack trace for the exception before the 'pricerange' one is shown below. As this happens frequently, we have also added some print statements to see what causes the out of range exception:


> domain: restaurant
> Slot pair [['Ref', '24248246']]
> Sys Dialogue Act {'Booking-Book': [['Ref', '24248246']]}
> Error value is 24248246 in domain restaurant

> Process Process-3:
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
>     self.run()
>   File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/philipjg/dstc8/ConvLab/convlab/experiment/control.py", line 35, in mp_run_session
>     metrics = session.run()
>   File "/home/philipjg/dstc8/ConvLab/convlab/experiment/control.py", line 170, in run
>     self.run_rl()
>   File "/home/philipjg/dstc8/ConvLab/convlab/experiment/control.py", line 133, in run_rl
>     self.try_ckpt(self.agent, self.env)
>   File "/home/philipjg/dstc8/ConvLab/convlab/experiment/control.py", line 87, in try_ckpt
>     self.num_eval)
>   File "/home/philipjg/dstc8/ConvLab/convlab/experiment/analysis.py", line 68, in gen_avg_result
>     returns.append(gen_result(agent, env))
>   File "/home/philipjg/dstc8/ConvLab/convlab/experiment/analysis.py", line 59, in gen_result
>     _return = gen_return(agent, env)
>   File "/home/philipjg/dstc8/ConvLab/convlab/experiment/analysis.py", line 35, in gen_return
>     next_obs, reward, done, info = env.step(action)
>   File "/home/philipjg/dstc8/ConvLab/convlab/env/multiwoz.py", line 248, in step
>     env_info_dict = self.u_env.step(action)
>   File "/home/philipjg/dstc8/ConvLab/convlab/env/multiwoz.py", line 122, in step
>     self.evaluator.add_sys_da(self.get_sys_act())
>   File "/home/philipjg/dstc8/ConvLab/convlab/evaluator/multiwoz.py", line 120, in add_sys_da
>     raise e
>   File "/home/philipjg/dstc8/ConvLab/convlab/evaluator/multiwoz.py", line 108, in add_sys_da
>     self.booked[self.cur_domain] = dbs[self.cur_domain][int(value)]
> IndexError: list index out of range

This seems to be reproducible (we assume based on fixed random seed) for some specific setups, and doesn't occur for others.

I hope this helps.

Cheers,
Philip

**Comment by xylankant** [comment] 2019-09-04 14:06
Update:

The two exceptions seem to me to be correlated. We are getting similar exceptions on a different training run. This time, the index out of range is thrown by trying to book a restaurant
> domain: restaurant                                                                                                                                                                                                                                                                                                                                                                                       > Slot pair [['Ref', '11749884']]
> Sys Dialogue Act {'Booking-Book': [['Ref', '11749884']]}
> Error value is 11749884 in domain restaurant

And then the next exception is the same as above, with "pricerange not in list"

**Comment by ggordonhall** [comment] 2019-09-05 09:08
Hi,

We've seen your latest commit, but we're not convinced that this will fix the issue.

Adding the `int(value) < len(dbs[self.cur_domain])` in `evaluator/multiwoz.py` will ignore reference numbers generated by `generate_ref_num`. This function is called in `MultiWozVocabActionDecoder` when the system has received the `Booking-Book` action (line 86 in `multiwoz_vocab_action_decoder.py`) and in `action_decorder` in `policy/system/multiwoz.util.py`.

These reference numbers are randomly generated 8 digit numbers and, unlike those generated in `dbquery.py` (line 63), exceed `len(dbs[self.cur_domain])`. We don't think that adding the length restriction fixes the problem, instead it seems that it will prevent the evaluator from recognizing valid bookings. Does the reference number need to be restricted by the length of the database in the first place?

Thanks,
Gabriel

**Closed** 2019-09-09 23:58 UTC
